# The name of your project.
name = "thebloomfoundation"
compatibility_date = "2023-10-30"

# Configuration for Cloudflare Pages builds
[pages_build]
build_command = "npm run build"
build_output_dir = "dist"